---
version: "3.5"

services:
  install_site:
    build: ./install_site
    ports:
      - 80:80
    environment:
      - DOMAIN=$DOMAIN
      - EMAIL=$EMAIL
    volumes:
      - ./nginx.conf:/web/jellyfin.conf
      - sites-availables:/sites-availables
      - certs:/etc/letsencrypt

  jellyfin:
    image: jellyfin/jellyfin
    networks:
      - selfhost

volumes:
  sites-availables:
    external: true
  certs:
    external: true

networks:
  selfhost:
    external: true
