---
version: "3.7"

services:
  install_site:
    build: install_site/
    ports:
      - "80:80"
    environment:
      - BASE_URL=$BASE_URL
      - EMAIL=$EMAIL
    volumes:
      - ./nginx.conf:/web/jellyfin.conf
      - sites-availables:/sites-availables
      - certs:/etc/letsencrypt

  jellyfin:
    image: jellyfin/jellyfin
    restart: always
    user: "$PUID:$PGID"
    volumes:
      - config:/config/
      - /media/:/media/
    env_file:
      - .env
    networks:
      - default
      - selfhost

volumes:
  config:
  sites-availables:
    external: true
  certs:
    external: true

networks:
  default:
  selfhost:
    external: true
